const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const KEY="my-life-dashboard-v1";
const todayISO=()=>{const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)};
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
let state=JSON.parse(localStorage.getItem(KEY)||"null")||{tasks:[],flights:[],subjects:["Wiskunde","Nederlands","Engels","Informatica"],settings:{name:"",theme:"dark",weekStart:1},focusSessions:0};
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const fmtDate=d=>new Intl.DateTimeFormat("nl-NL",{day:"numeric",month:"long",year:"numeric"}).format(new Date(d+"T12:00:00"));
const escapeHTML=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)}
function openModal(html){$("#modal").innerHTML=html;$("#modalBackdrop").classList.add("show")}
function closeModal(){$("#modalBackdrop").classList.remove("show")}
$("#modalBackdrop").addEventListener("click",e=>{if(e.target.id==="modalBackdrop")closeModal()});
function switchView(view){$$(".view").forEach(x=>x.classList.toggle("active",x.id==="view-"+view));$$(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.view===view));$("#viewTitle").textContent={dashboard:"Dashboard",tasks:"Taken",planning:"Planning",today:"Vandaag",agenda:"Agenda",school:"School",homework:"Huiswerk",flights:"Flight Sim",focus:"Focus",stats:"Statistieken",goals:"Doelen",settings:"Instellingen"}[view]||"Dashboard";if(innerWidth<760)$("#sidebar").classList.remove("open");render();location.hash=view}
$$(".nav-item").forEach(b=>b.onclick=()=>switchView(b.dataset.view));
$$("[data-goto]").forEach(b=>b.onclick=()=>switchView(b.dataset.goto));
$("#menuBtn").onclick=()=>$("#sidebar").classList.toggle("open");
$("#themeBtn").onclick=()=>{state.settings.theme=state.settings.theme==="light"?"dark":"light";document.body.classList.toggle("light",state.settings.theme==="light");save()};
$("#quickProfile").onclick=()=>switchView("settings");
document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();openTaskModal()}});
function greeting(){const h=new Date().getHours();const base=h<12?"Goedemorgen":h<18?"Goedemiddag":"Goedenavond";return state.settings.name?base+", "+escapeHTML(state.settings.name)+".":base+"."}
function renderHeader(){$("#greeting").innerHTML=greeting();$("#dateLabel").textContent=new Intl.DateTimeFormat("nl-NL",{weekday:"long",day:"numeric",month:"long"}).format(new Date());}
function taskByDate(date){return state.tasks.filter(t=>t.due===date)}
function todayMagister(){return (state.calendarEvents||[]).filter(e=>e.start&&new Date(e.start).toDateString()===new Date().toDateString()).sort((a,b)=>new Date(a.start)-new Date(b.start))}
function todayHomework(){return state.tasks.filter(t=>!t.done&&t.due===todayISO()&&(t.type==="school"||t.subject))}
function timeRange(e){const f=x=>new Intl.DateTimeFormat("nl-NL",{hour:"2-digit",minute:"2-digit"}).format(new Date(x));return e.start?(f(e.start)+(e.end?" – "+f(e.end):"")):""}
function taskHTML(t){return '<div class="task"><button class="check '+(t.done?"done":"")+'" data-complete="'+t.id+'">'+(t.done?"✓":"")+'</button><div class="task-main"><div class="task-title '+(t.done?"done-text":"")+'">'+escapeHTML(t.title)+'</div><div class="task-meta">'+escapeHTML(t.subject||"Algemeen")+' · '+(t.due?fmtDate(t.due):"Geen deadline")+'</div></div><i class="priority-dot '+t.priority+'"></i><button class="icon-btn" data-delete="'+t.id+'">×</button></div>'}
function bindTaskButtons(){ $$("[data-complete]").forEach(b=>b.onclick=()=>{const t=state.tasks.find(x=>x.id===b.dataset.complete);t.done=!t.done;save();render()});$$("[data-delete]").forEach(b=>b.onclick=()=>{state.tasks=state.tasks.filter(x=>x.id!==b.dataset.delete);save();render();toast("Taak verwijderd")})}
function renderDashboard(){const open=state.tasks.filter(t=>!t.done),done=state.tasks.filter(t=>t.done),today=taskByDate(todayISO()),week=state.tasks.filter(t=>{const d=new Date();const x=new Date(t.due+"T12:00:00");return t.due&&x>=new Date(d.getFullYear(),d.getMonth(),d.getDate())&&x<=new Date(d.getFullYear(),d.getMonth(),d.getDate()+7)});$("#statOpen").textContent=open.length;$("#statToday").textContent=today.filter(t=>!t.done).length;$("#statWeek").textContent=week.filter(t=>!t.done).length;$("#statDone").textContent=done.length;const list=today.filter(t=>!t.done).slice(0,6);$("#todayList").classList.toggle("empty-state",!list.length);$("#todayList").innerHTML=list.length?list.map(taskHTML).join():'<div class="empty-icon">✓</div><strong>Je bent helemaal bij</strong><span>Voeg iets toe als er nog iets op je wacht.</span>';bindTaskButtons();const total=week.length,wd=week.filter(t=>t.done).length,pct=total?Math.round(wd/total*100):0;$("#weekPct").textContent=pct+"%";$("#weekRing").style.background='conic-gradient(var(--accent) '+pct*3.6+'deg,var(--surface3) 0deg)';$("#legendDone").textContent=wd;$("#legendOpen").textContent=total-wd;const f=state.flights.at(-1);$("#lastFlight").innerHTML=f?'<div class="flight-route"><strong>'+escapeHTML(f.dep)+' → '+escapeHTML(f.arr)+'</strong><span>'+escapeHTML(f.aircraft||"Aircraft")+' · '+f.distance+' NM · ★ '+f.rating+'</span></div>':'<div class="empty-icon">✈</div><strong>Nog geen vluchten</strong><span>Log je eerste vlucht.</span>'}
function renderTasks(){let a=[...state.tasks];const q=($("#taskSearch")?.value||"").toLowerCase(),filter=$("#taskFilter")?.value||"all",pri=$("#taskPriority")?.value||"all";a=a.filter(t=>(!q||(t.title+" "+(t.subject||"")).toLowerCase().includes(q))&&(filter==="all"||(filter==="open"&&!t.done)||(filter==="done"&&t.done)||(filter==="today"&&t.due===todayISO()))&&(pri==="all"||t.priority===pri));$("#allTasks").innerHTML=a.length?a.map(taskHTML).join():'<div class="panel empty-state"><div class="empty-icon">✓</div><strong>Geen taken gevonden</strong><span>Probeer een andere filter of voeg een taak toe.</span></div>';bindTaskButtons()}
function renderSchool(){const counts=Object.fromEntries(state.subjects.map(s=>[s,0]));state.tasks.filter(t=>!t.done&&t.subject).forEach(t=>counts[t.subject]=(counts[t.subject]||0)+1);$("#subjects").innerHTML=state.subjects.map(s=>'<div class="subject"><span><i></i>'+escapeHTML(s)+'</span><b>'+((counts[s]||0))+'</b></div>').join("");const a=state.tasks.filter(t=>t.subject&&!t.done);$("#schoolCount").textContent=a.length+" open";$("#schoolTasks").innerHTML=a.length?a.map(taskHTML).join():'<div class="empty-state"><div class="empty-icon">▣</div><strong>Geen schoolwerk open</strong><span>Je kunt even ademhalen.</span></div>';bindTaskButtons()}
let calDate=new Date();
function renderCalendar(){const y=calDate.getFullYear(),m=calDate.getMonth();$("#monthTitle").textContent=new Intl.DateTimeFormat("nl-NL",{month:"long",year:"numeric"}).format(calDate);const first=new Date(y,m,1),last=new Date(y,m+1,0),offset=(first.getDay()-1+7)%7;let html=["ma","di","wo","do","vr","za","zo"].map(x=>'<div class="cal-name">'+x+"</div>").join("");for(let i=0;i<offset;i++)html+='<div class="cal-day muted"></div>';for(let d=1;d<=last.getDate();d++){const iso=y+"-"+String(m+1).padStart(2,"0")+"-"+String(d).padStart(2,"0"),tasks=taskByDate(iso),events=(state.calendarEvents||[]).filter(e=>{const z=new Date(e.start);return z.getFullYear()===y&&z.getMonth()===m&&z.getDate()===d});html+='<div class="cal-day '+(iso===todayISO()?"today":"")+'" data-date="'+iso+'"><div class="cal-num">'+d+"</div>"+tasks.slice(0,3).map(t=>'<div class="cal-task">'+escapeHTML(t.title)+"</div>").join("")+events.slice(0,3).map(e=>'<div class="cal-task integration-event">'+escapeHTML(e.title)+" · "+(e.location?escapeHTML(e.location):"Magister")+"</div>").join("")+"</div>"}$("#calendar").innerHTML=html;$$("[data-date]").forEach(x=>x.onclick=()=>openTaskModal(x.dataset.date))}
$("#prevMonth").onclick=()=>{calDate.setMonth(calDate.getMonth()-1);renderCalendar()};$("#nextMonth").onclick=()=>{calDate.setMonth(calDate.getMonth()+1);renderCalendar()};
function renderFlights(){const fs=state.flights,dist=fs.reduce((a,f)=>a+Number(f.distance||0),0),mins=fs.reduce((a,f)=>a+Number(f.duration||0),0),avg=fs.length?(fs.reduce((a,f)=>a+Number(f.rating||0),0)/fs.length).toFixed(1):"—";$("#flightCount").textContent=fs.length;$("#flightDistance").textContent=dist.toLocaleString("nl-NL");$("#flightTime").textContent=Math.floor(mins/60)+"h "+mins%60+"m";$("#flightRating").textContent=avg==="—"?"—":"★ "+avg;const q=($("#flightSearch")?.value||"").toLowerCase(),arr=fs.filter(f=>(f.dep+" "+f.arr+" "+f.aircraft).toLowerCase().includes(q)).reverse();$("#flightList").innerHTML=arr.length?'<div class="flight-row head"><span>Datum</span><span>Route</span><span>Aircraft</span><span>Afstand</span><span>Rating</span></div>'+arr.map(f=>'<div class="flight-row"><span>'+escapeHTML(f.date)+'</span><strong>'+escapeHTML(f.dep)+' → '+escapeHTML(f.arr)+'</strong><span>'+escapeHTML(f.aircraft||"—")+'</span><span>'+f.distance+' NM</span><span>★ '+f.rating+'</span></div>').join():'<div class="empty-state"><div class="empty-icon">✈</div><strong>Geen vluchten</strong><span>Log je eerste vlucht.</span></div>'}
function renderStats(){const total=state.tasks.length,done=state.tasks.filter(t=>t.done).length;$("#totalTasks").textContent=total;$("#completion").textContent=(total?Math.round(done/total*100):0)+"%";$("#statHours").textContent=Math.floor(state.flights.reduce((a,f)=>a+Number(f.duration||0),0)/60)+"h";$("#focusSessions").textContent=state.focusSessions||0;const c={high:0,medium:0,low:0};state.tasks.forEach(t=>c[t.priority]=(c[t.priority]||0)+1);const max=Math.max(1,...Object.values(c));$("#priorityChart").innerHTML=[["Hoog","high"],["Gemiddeld","medium"],["Laag","low"]].map(([n,k])=>'<div class="bar-row"><span>'+n+'</span><div class="bar-track"><div class="bar-fill" style="width:'+c[k]/max*100+'%"></div></div><b>'+c[k]+'</b></div>').join("")}

function homeAIWidgets(){try{return JSON.parse(localStorage.getItem("my-life-ai-widgets-v1")||"[]")}catch{return[]}}
function homeWidgetDoc(w){const html=String(w.html||""),css=String(w.css||""),js=String(w.js||"").replace(/<\\/script/gi,"<\\/script");const data={today:todayISO(),tasks:(state.tasks||[]).slice(0,100),calendarEvents:(state.calendarEvents||[]).slice(0,100),flights:(state.flights||[]).slice(-50),goals:(()=>{try{return JSON.parse(localStorage.getItem("my-life-goals-v1")||"[]")}catch{return[]}})()};return '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>html,body{margin:0;min-height:100%;background:transparent;color:#f5f8fb;font-family:Inter,system-ui,sans-serif}*{box-sizing:border-box}'+css+'</style></head><body>'+html+'<script>window.MyLifeWidgetData='+JSON.stringify(data).replace(/<\\//g,"<\\/")+';<\\/script><script>'+js+'<\\/script></body></html>'}
function renderHomeAIWidgets(){const box=$("#homeAIWidgets");if(!box)return;const all=homeAIWidgets(),items=all.filter(w=>w.home===true);if(!items.length){box.innerHTML='<div class="empty-state small"><strong>Nog geen AI-widgets op Home</strong><span>Maak of open een widget via AI → Widget Lab en kies “Toevoegen aan Home”.</span></div>';return}box.innerHTML=items.map((w,i)=>'<article class="home-ai-widget"><div class="home-ai-widget-head"><div><span class="panel-kicker">AI WIDGET</span><h3>'+escapeHTML(w.name||"Eigen widget")+'</h3></div><button class="icon-btn" title="Van Home verwijderen" data-home-widget="'+escapeHTML(w.id||String(i))+'">×</button></div><iframe class="home-ai-widget-frame" sandbox="allow-scripts" loading="lazy" title="'+escapeHTML(w.name||"AI widget")+'"></iframe></article>').join("");items.forEach((w,i)=>{const frame=box.querySelectorAll("iframe")[i];if(frame)frame.srcdoc=homeWidgetDoc(w)});box.querySelectorAll("[data-home-widget]").forEach(b=>b.onclick=()=>{const a=homeAIWidgets();const w=a.find(x=>String(x.id)===String(b.dataset.homeWidget));if(w){w.home=false;localStorage.setItem("my-life-ai-widgets-v1",JSON.stringify(a));renderHomeAIWidgets();toast("Widget van Home verwijderd")}})}
window.addEventListener("my-life-ai-widgets-updated",renderHomeAIWidgets);
function renderDashboardExtras(){
 const schedule=$("#dashboardSchedule"), hw=$("#dashboardHomework"), summary=$("#dashboardDaySummary"), goals=$("#dashboardGoals");
 const events=todayMagister(), home=todayHomework(), allToday=taskByDate(todayISO()), doneToday=allToday.filter(t=>t.done).length;
 if(schedule)schedule.innerHTML=events.length?events.slice(0,6).map(e=>'<div class="schedule-item"><div class="schedule-time">'+timeRange(e)+'</div><div class="schedule-main"><strong>'+escapeHTML(e.title)+'</strong><span>'+escapeHTML(e.location||"Lokaal onbekend")+'</span></div></div>').join(""):'<div class="empty-state"><strong>Geen rooster voor vandaag</strong><span>Synchroniseer Magister bij Integraties.</span></div>';
 if(hw)hw.innerHTML=home.length?home.slice(0,5).map(taskHTML).join(""):'<div class="empty-state"><strong>Geen huiswerk voor vandaag</strong><span>Dat ziet er rustig uit. 🎉</span></div>';
 if(summary)summary.innerHTML='<div class="summary-stat"><strong>'+events.length+'</strong><span>Lessen</span></div><div class="summary-stat"><strong>'+home.length+'</strong><span>Huiswerk</span></div><div class="summary-stat"><strong>'+allToday.length+'</strong><span>Vandaag</span></div><div class="summary-stat"><strong>'+doneToday+'</strong><span>Klaar</span></div>';
 const gs=JSON.parse(localStorage.getItem("my-life-goals-v1")||"[]");
 if(goals)goals.innerHTML=gs.length?gs.slice(0,3).map(g=>'<div class="goal-mini-row"><span>'+escapeHTML(g.title)+'</span><b>'+Math.round((Number(g.current)||0)/(Number(g.target)||1)*100)+'%</b></div>').join(""):'<div class="empty-state small"><strong>Nog geen doelen</strong><span>Maak je eerste doel.</span></div>';
}
window.addEventListener("my-life-data-updated",()=>{try{const fresh=JSON.parse(localStorage.getItem(KEY)||"{}");state={...state,...fresh};render()}catch(e){console.error(e)}});
function render(){renderHeader();renderDashboard();renderDashboardExtras();renderHomeAIWidgets();if($("#view-tasks").classList.contains("active"))renderTasks();renderCalendar();renderSchool();renderFlights();renderStats();$("#nameInput").value=state.settings.name||"";$("#weekStart").value=state.settings.weekStart}
function openTaskModal(date=todayISO()){openModal('<h2>Nieuwe taak</h2><p>Zet het uit je hoofd en in je dashboard.</p><form id="taskForm"><div class="form-grid"><div class="form-field full"><label>Taak</label><input name="title" required autofocus placeholder="Bijv. wiskunde leren"></div><div class="form-field"><label>Datum</label><input type="date" name="due" value="'+date+'"></div><div class="form-field"><label>Prioriteit</label><select name="priority"><option value="high">Hoog</option><option value="medium" selected>Gemiddeld</option><option value="low">Laag</option></select></div><div class="form-field"><label>Onderdeel</label><select name="subject"><option value="">Algemeen</option>'+state.subjects.map(s=>'<option>'+escapeHTML(s)+"</option>").join("")+'</select></div><div class="form-field"><label>Type</label><select name="type"><option value="task">Taak</option><option value="school">Schoolwerk</option></select></div></div><div class="modal-actions"><button type="button" class="ghost-btn" id="cancelModal">Annuleren</button><button class="primary-btn">Toevoegen</button></div></form>');$("#cancelModal").onclick=closeModal;$("#taskForm").onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);state.tasks.push({id:uid(),title:f.get("title"),due:f.get("due"),priority:f.get("priority"),subject:f.get("subject"),type:f.get("type"),done:false});save();closeModal();render();toast("Taak toegevoegd")}}
function openFlightModal(){openModal('<h2>Vlucht loggen</h2><p>Een simpele flight-sim log, opgeslagen in je browser.</p><form id="flightForm"><div class="form-grid"><div class="form-field"><label>Datum</label><input type="date" name="date" value="'+todayISO()+'" required></div><div class="form-field"><label>Aircraft</label><input name="aircraft" placeholder="A321neo"></div><div class="form-field"><label>Vertrek</label><input name="dep" placeholder="LIRF" maxlength="4" required></div><div class="form-field"><label>Aankomst</label><input name="arr" placeholder="EDDF" maxlength="4" required></div><div class="form-field"><label>Afstand (NM)</label><input type="number" name="distance" min="0" value="0"></div><div class="form-field"><label>Vliegtijd (min)</label><input type="number" name="duration" min="0" value="60"></div><div class="form-field"><label>Rating / 5</label><input type="number" name="rating" min="0" max="5" step=".1" value="5"></div></div><div class="modal-actions"><button type="button" class="ghost-btn" id="cancelModal">Annuleren</button><button class="primary-btn">Log vlucht</button></div></form>');$("#cancelModal").onclick=closeModal;$("#flightForm").onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);state.flights.push({date:f.get("date"),aircraft:f.get("aircraft"),dep:f.get("dep").toUpperCase(),arr:f.get("arr").toUpperCase(),distance:Number(f.get("distance")),duration:Number(f.get("duration")),rating:Number(f.get("rating"))});save();closeModal();render();toast("Vlucht opgeslagen")}}
function openSubjectModal(){openModal('<h2>Vak toevoegen</h2><p>Maak je schoolhub passend bij jouw rooster.</p><form id="subjectForm"><div class="form-field"><label>Naam vak</label><input name="subject" required placeholder="Bijv. geschiedenis"></div><div class="modal-actions"><button type="button" class="ghost-btn" id="cancelModal">Annuleren</button><button class="primary-btn">Toevoegen</button></div></form>');$("#cancelModal").onclick=closeModal;$("#subjectForm").onsubmit=e=>{e.preventDefault();const n=new FormData(e.target).get("subject");if(!state.subjects.includes(n))state.subjects.push(n);save();closeModal();render();toast("Vak toegevoegd")}}
$("#quickAdd").onclick=openTaskModal;$("#taskAdd2").onclick=openTaskModal;$("#planAdd").onclick=()=>openTaskModal();$("#schoolAdd").onclick=()=>{openTaskModal();setTimeout(()=>{const x=document.querySelector('[name="type"]');if(x)x.value="school"},0)};$("#flightAdd").onclick=openFlightModal;$("#addSubject").onclick=openSubjectModal;$$("[data-action]").forEach(b=>b.onclick=()=>b.dataset.action==="task"?openTaskModal():b.dataset.action==="flight"?openFlightModal():switchView(b.dataset.action));
["taskSearch","taskFilter","taskPriority","flightSearch"].forEach(id=>$("#"+id)?.addEventListener("input",render));
$("#saveSettings").onclick=()=>{state.settings.name=$("#nameInput").value.trim();state.settings.weekStart=Number($("#weekStart").value);save();render();toast("Instellingen opgeslagen")};
$("#clearData").onclick=()=>{if(confirm("Alles wissen? Dit kan niet ongedaan worden.")){localStorage.removeItem(KEY);location.reload()}};
$("#demoData").onclick=()=>{state.tasks=[{id:uid(),title:"Huiswerk plannen",due:todayISO(),priority:"high",subject:"Informatica",type:"school",done:false},{id:uid(),title:"30 minuten leren",due:todayISO(),priority:"medium",subject:"Wiskunde",type:"school",done:false},{id:uid(),title:"Flight sim vlucht voorbereiden",due:todayISO(),priority:"low",subject:"",type:"task",done:false}];state.flights=[{date:todayISO(),aircraft:"A321neo",dep:"LIRF",arr:"EDDF",distance:540,duration:85,rating:4.8}];save();render();toast("Voorbeelddata geladen")};

let timerMinutes=25,timerSeconds=0,timerRunning=false,timerInterval;
function updateTimer(){const s=String(timerSeconds).padStart(2,"0");$("#timer").textContent=String(timerMinutes).padStart(2,"0")+":"+s}
$$(".timer-mode button").forEach(b=>b.onclick=()=>{if(timerRunning)return;$$(".timer-mode button").forEach(x=>x.classList.remove("active"));b.classList.add("active");timerMinutes=Number(b.dataset.min);timerSeconds=0;updateTimer()});
$("#timerStart").onclick=()=>{if(timerRunning){clearInterval(timerInterval);timerRunning=false;$("#timerStart").textContent="Verder";$("#timerStatus").textContent="Gepauzeerd.";return}timerRunning=true;$("#timerStart").textContent="Pauze";$("#timerStatus").textContent="Focus bezig…";timerInterval=setInterval(()=>{if(timerSeconds===0){if(timerMinutes===0){clearInterval(timerInterval);timerRunning=false;state.focusSessions=(state.focusSessions||0)+1;save();$("#timerStart").textContent="Start opnieuw";$("#timerStatus").textContent="Sessie afgerond. Lekker bezig.";toast("Focus sessie afgerond");return}timerMinutes-- ;timerSeconds=59}else timerSeconds--;updateTimer()},1000)};
$("#timerReset").onclick=()=>{clearInterval(timerInterval);timerRunning=false;timerMinutes=Number($(".timer-mode button.active")?.dataset.min||25);timerSeconds=0;$("#timerStart").textContent="Start focus";$("#timerStatus").textContent="Klaar wanneer jij dat bent.";updateTimer()};
document.body.classList.toggle("light",state.settings.theme==="light");
if(location.hash.slice(1)&&$("#view-"+location.hash.slice(1)))switchView(location.hash.slice(1));else render();
